name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

env:
  CLOUDRUN_NAME: fastapicloudrun
  REGION: us-central1
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLOUDREGISTRY_IMAGE: gcr.io/$GCP_PROJECT_ID/$CLOUDRUN_NAME:latest
  REGISTRY_NAME: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.CLOUDRUN_NAME }}:${{ github.sha }}" ./
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.CLOUDRUN_NAME }}:${{ github.sha }}"


      # Deploy to Cloud Run
      # NOte: Allowing unauthenticated requests has to be done in the Cloud Run console
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.CLOUDRUN_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.CLOUDRUN_NAME }}:${{ github.sha }}
          env_vars: |- 
            SERVICE=${{ env.CLOUDRUN_NAME }}